# Generated by Django 4.2.3 on 2023-07-31 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('Company_namee', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('manager_id', models.IntegerField()),
                ('department_id', models.IntegerField()),
                ('fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.company')),
            ],
        ),
    ]
